# Generated by Django 5.1.4 on 2026-06-23 03:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("make", models.CharField(db_index=True, max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(help_text="Mileage in kilometers"),
                ),
                (
                    "engine_cc",
                    models.PositiveIntegerField(help_text="Engine displacement in CC"),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("PETROL", "Petrol"),
                            ("DIESEL", "Diesel"),
                            ("ELECTRIC", "Electric"),
                        ],
                        default="PETROL",
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="GOOD",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "images",
                    models.JSONField(
                        default=list, help_text="List of image URLs/paths"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bike",
                "verbose_name_plural": "Bikes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "start_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum price for the auction to be valid (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_increment",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        help_text="Minimum bid increment in INR",
                        max_digits=10,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_auctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction",
                        to="auctions.bike",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction",
                "verbose_name_plural": "Auctions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auctions.auction",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["auction", "-amount"],
                        name="auctions_bi_auction_5888cb_idx",
                    ),
                    models.Index(
                        fields=["bidder", "-created_at"],
                        name="auctions_bi_bidder__c14e80_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "start_time"], name="auctions_au_status_d4eee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "end_time"], name="auctions_au_status_ced721_idx"
            ),
        ),
    ]
